const fs = require('fs');
const path = require('path');

const srcRenderer = path.join(__dirname, '..', 'src', 'renderer');
const distRenderer = path.join(__dirname, '..', 'dist', 'renderer');

const copyFile = (src, dest) => {
  const destDir = path.dirname(dest);
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }
  fs.copyFileSync(src, dest);
  console.log(`Copied: ${path.relative(process.cwd(), src)} -> ${path.relative(process.cwd(), dest)}`);
};

const copyDir = (src, dest) => {
  if (!fs.existsSync(src)) {
    return;
  }
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      copyFile(srcPath, destPath);
    }
  }
};

// Copy index.html
copyFile(
  path.join(srcRenderer, 'index.html'),
  path.join(distRenderer, 'index.html')
);

// Copy styles directory
copyDir(
  path.join(srcRenderer, 'styles'),
  path.join(distRenderer, 'styles')
);

// Copy assets directory
copyDir(
  path.join(srcRenderer, 'assets'),
  path.join(distRenderer, 'assets')
);

// Copy gsap for renderer usage
const gsapSrc = path.join(__dirname, '..', 'node_modules', 'gsap', 'dist', 'gsap.min.js');
const gsapDest = path.join(distRenderer, 'vendor', 'gsap.min.js');
if (fs.existsSync(gsapSrc)) {
  copyFile(gsapSrc, gsapDest);
}

// Copy config window assets
const srcConfig = path.join(srcRenderer, 'config');
const distConfig = path.join(distRenderer, 'config');

// Copy config window HTML
const configHtmlSrc = path.join(srcConfig, 'index.html');
if (fs.existsSync(configHtmlSrc)) {
  copyFile(configHtmlSrc, path.join(distConfig, 'index.html'));
}

// Copy config window styles
copyDir(
  path.join(srcConfig, 'styles'),
  path.join(distConfig, 'styles')
);

// Copy config window assets (logo, etc.)
copyDir(
  path.join(srcConfig, 'assets'),
  path.join(distConfig, 'assets')
);

// Build the wizard's translation bundle.
//
// The locales are JSON so a wording fix never means editing TypeScript. The
// wizard has no module loader and lives on a file:// URL, where Chromium blocks
// fetch() and XHR outright, so the only way to get data into the page is a
// <script> tag. This generates one from the JSON.
const localesDir = path.join(srcConfig, 'locales');
if (fs.existsSync(localesDir)) {
  const bundle = {};
  for (const entry of fs.readdirSync(localesDir).sort()) {
    if (!entry.endsWith('.json')) continue;
    const language = path.basename(entry, '.json');
    bundle[language] = JSON.parse(fs.readFileSync(path.join(localesDir, entry), 'utf-8'));
  }

  const generated =
    '// Generated by scripts/copy-assets.js from src/renderer/config/locales/*.json\n' +
    '// Do not edit: change the JSON instead.\n' +
    `window.configTranslations = ${JSON.stringify(bundle, null, 2)};\n`;

  const target = path.join(distConfig, 'scripts', 'translations.js');
  const targetDir = path.dirname(target);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  fs.writeFileSync(target, generated, 'utf-8');
  console.log(
    `Generated: ${path.relative(process.cwd(), target)} (${Object.keys(bundle).join(', ')})`
  );
}

// Copy app logo to dist root (for taskbar icon)
const logoSrc = path.join(__dirname, '..', 'logo.png');
const logoDest = path.join(__dirname, '..', 'dist', 'logo.png');
if (fs.existsSync(logoSrc)) {
  copyFile(logoSrc, logoDest);
}

// Copy ICO for Windows taskbar/title bar icon
const icoSrc = path.join(__dirname, '..', 'logo.ico');
const icoDest = path.join(__dirname, '..', 'dist', 'logo.ico');
if (fs.existsSync(icoSrc)) {
  copyFile(icoSrc, icoDest);
}

console.log('Assets copied successfully.');
